Solve env problems and create the first test case
PimpAPP/pimp-site pull request #3
Opened 2018-04-16 19:03 UTC by jvcsizilio

Teste do tipo e2e para o cadastro do Catador.
Correções no ambiente para que o teste funcione corretamente.
Qualquer dúvida estou a disposição

2018-04-17 03:16 UTC, luislhl requested changes
Eu to levando uns erros aqui, queria ver contigo se fiz algo errado ou se tá quebrado mesmo.

Tudo que fiz foi entrar na branch e rodar `npm install` pra atualizar os pacotes.
No `postinstall` tá configurado pra rodar o comando `ng build --aot -prod`. (Que imagino ser o comando pra buildar pra prod)

Mas quando ele foi rodar esse comando, deu vários erros parecidos com esse:
```
ERROR in ng:///Users/luizhelder/Workspace/cataki/pimp-site/src/app/cadastro/cadastro.component.html (237,49): Property 'whatsapp' does not exist on type 'Phone'
```

Pelo que vi, tem algumas linhas parecidas com essa no `cadastro.component.html`: 
```
[(ngModel)]="catador.phones[0].whatsapp"
```

E como tu mudou no `models/phone.ts` de `whatsapp` para `has_whatsapp`, tá acontecendo esse erro.

Se não for isso e eu tiver fazendo algo errado, me avisa aí que tento de novo.

2018-04-17 12:03 UTC, jvcsizilio commented
@luislhl A questão do Phone eu resolvei e commitei. 
A respeito do ambiente, caso ocorra algum erro sugiro que você apague pasta node_modules do projeto e rode o npm install novamente. Pelo menos no meu caso eu precisei isso para funcionar.

2018-05-09 13:18 UTC, jvcsizilio commented
@luislhl Concordo com vc. Vamos fazer!

2018-05-25 01:36 UTC, luislhl commented
@jvcsizilio , eu rodei os testes e estão passando.
Porém, ao rodar o teste de editar o catador, um erro ocorre no servidor. A parte importante é essa:
```
  File "/Users/luizhelder/Workspace/cataki/pimpapp-api/app_site/api/views.py", line 395, in edit_catador
    m.has_whatsapp = int(phone.get('whatsapp'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Me corrija se eu estiver errado, mas parece que a mudança que você está fazendo no model Phone no front-end vai quebrar o site, porque o servidor está esperando que venha o campo `whatsapp` em vez de `has_whatsapp`.

Teria que ser alterado esse nome também no servidor, aparentemente.

Outra coisa é que o ideal seria que os testes e2e falhassem quando der erro no servidor, mas todos passaram. Então os testes não estão realmente testando o fluxo inteiro, pois não estão verificando se o retorno do servidor é o esperado, certo?

2018-05-26 13:16 UTC, jvcsizilio commented
@luislhl Os testes precisam ser rodados com o PR test-initial no lado do servidor também. Acredito que os erros ocorreram por causa disso. Certifique-se por favor de que vc está no branch correto la na API.

A respeito dos testes falharem ao ocorrer um erro no servidor, você tem razão. Os testes e2e verifica se a mensagem "Cadastro realizado com sucesso" irá aparecer. No caso, imagino que o erro está no site então, visto que ele deveria ter retornado uma mensagem diferente caso um erro ocorresse.

2018-05-31 15:15 UTC, luislhl approved these changes
@jvcsizilio , tinha esquecido desse detalhe de rodar a API na branch `test-initial`.
Agora fiz isso e os testes passaram sem erros no servidor, então to aprovando.

O único detalhe é aquele de o teste não estar falhando quando dá erro na API.
Isso é ruim se esses testes forem incluídos num CI, por exemplo, porque o CI vai falar que os testes estão passando mesmo que ocorra um erro no servidor.

2018-06-14 23:16 UTC, evandroguedes commented
@jvcsizilio precisa resolver esse conflito. Seria ótimo já fechar essa PR também e fazer o merge.

2018-06-18 11:44 UTC, merged